name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual workflow runs
  workflow_dispatch:
  # Run on pushes to main branch (for immediate updates)
  push: {branches: ["main"]}

jobs:
  # Base Metrics - General GitHub stats and activity
  base:
    permissions: write-all
    name: Base metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          use_prebuilt_image: yes
          optimize: svg
          config_display: large
          config_padding: 10%

  # Activity - Recent GitHub activity visualization
  activity:
    permissions: write-all
    name: Activity metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          config_timezone: Asia/Kolkata
          use_prebuilt_image: yes
          optimize: svg

  # Isocalendar - Contribution calendar in isometric view
  isocalendar:
    permissions: write-all
    name: Isocalendar metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          use_prebuilt_image: yes
          optimize: svg

  # Languages - Programming languages usage stats
  languages:
    permissions: write-all
    name: Language metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_categories: markup, programming, data
          plugin_languages_indepth: yes
          use_prebuilt_image: yes
          optimize: svg

  # Follow-up - Issues and PRs metrics
  followup:
    permissions: write-all
    name: Follow-up metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-followup.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          use_prebuilt_image: yes
          optimize: svg

  # People - Followers and following visualization
  people:
    permissions: write-all
    name: People metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-people.svg
          base: ""
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_identicons: no
          plugin_people_thanks: no
          use_prebuilt_image: yes
          optimize: svg
