name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  base:
    permissions:
      contents: write
    name: Base metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: manankumar7403
          filename: github-metrics-base.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          use_prebuilt_image: yes
          optimize: svg
          config_display: medium
          config_font_size: 10 # Reduced from 12
          config_padding: 10%
          config_output: svg, width=600, height=800 # Reduced from 800x1000
          output_action: commit
          committer_name: manankumar7403
          committer_email: manantemp1404@gmail.com
          commit_message: "Update github-metrics-base.svg"

  activity:
    permissions:
      contents: write
    name: Activity metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: manankumar7403
          filename: github-metrics-activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          config_timezone: Asia/Kolkata
          config_font_size: 12
          config_output: svg, width=600, height=400 # Reduced from 800x500
          optimize: svg
          output_action: commit
          committer_name: manankumar7403
          committer_email: manantemp1404@gmail.com
          commit_message: "Update github-metrics-activity.svg"

  isocalendar:
    permissions:
      contents: write
    name: Isocalendar metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: manankumar7403
          filename: github-metrics-isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_font_size: 12
          config_output: svg, width=800, height=400
          optimize: svg
          output_action: commit
          committer_name: manankumar7403
          committer_email: manantemp1404@gmail.com
          commit_message: "Update github-metrics-isocalendar.svg"

  languages:
    permissions:
      contents: write
    name: Language metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: manankumar7403
          filename: github-metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, prose, data
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming, prose, data
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          repositories_skipped: ""
          commits_authoring: manantemp1404@gmail.com, manankumar7403, Manan Kumar
          config_font_size: 10 # Reduced from 12
          config_output: svg, width=600, height=400 # Reduced from 800x400
          optimize: svg
          output_action: commit
          committer_name: manankumar7403
          committer_email: manantemp1404@gmail.com
          commit_message: "Update github-metrics-languages.svg"

  followup:
    permissions:
      contents: write
    name: Follow-up metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: manankumar7403
          filename: github-metrics-followup.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          config_font_size: 12
          config_output: svg, width=600, height=400 # Reduced from 800x400
          optimize: svg
          output_action: commit
          committer_name: manankumar7403
          committer_email: manantemp1404@gmail.com
          commit_message: "Update github-metrics-followup.svg"

  people:
    permissions:
      contents: write
    name: People metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: manankumar7403
          filename: github-metrics-people.svg
          base: ""
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 12
          plugin_people_size: 20
          plugin_people_identicons: no
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          retries: 3
          retry_wait: 10
          config_font_size: 12
          config_output: svg, width=800, height=500
          optimize: svg
          output_action: commit
          committer_name: manankumar7403
          committer_email: manantemp1404@gmail.com
          commit_message: "Update github-metrics-people.svg"
