name: GitHub 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC (8:00 AM IST)
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    permissions:
      contents: write # Explicitly grant write permissions for committing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Ensure write access for commit

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.6.0 # Downgraded to a stable version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Default token
          USERNAME: ${{ github.repository_owner }} # e.g., manankumar7403
          THEME: nightgreen

      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff-index --quiet HEAD || git commit -m "Update 3D Contribution Graph"
          git push
